### ISSUE TITLE
EXECUTION.FEE

### ISSUE THREAD

**Issue by ramonck** [bmino/binance-triangle-arbitrage#125]
From what I remember the fees are: 0.0075% fee
I see you have it configured as the following and was wondering what you have it considered? "FEE": 0.10

**Comment by bmino** [comment]
Binance lists their fees here: [https://www.binance.com/en/fee/schedule](https://www.binance.com/en/fee/schedule)

Fees with no discounts: 0.10%
Fees with a basic BNB discount: 0.075%

So you have a point where perhaps the default should be `0.075` instead of `0.1`
Keep in mind this value is provided as a percent and not as a decimal as per the config readme

**Comment by ramonck** [comment]
Thanks for the return, changed the config.
