### ISSUE TITLE
Too Many Trades Per Second

### ISSUE THREAD

**Issue by kuuulwin** [bmino/binance-triangle-arbitrage#44]
Hello. While working with parallel execution. I have come upon a brick wall that is Binance limits. 
With low profit settings and calculations you're able to execute more than 10 trades per second. 
Is there a way to move the limit from 10 to 9 ? So they would finish how they started.

**Comment by bmino** [comment]
Okay, so let me ensure I understand the issue.

When trades are executing quickly, let's say that 9 trades are executed in the first half of a second.
Then another arbitrage pair is identified (which would require 3 trades) and only the first is executed before the trade limit is reached and the final 2 trades are blocked?

**Comment by kuuulwin** [comment]
Yes, that's correct. In volatile markets BTC and ETH trades can overlap and all your funds are stuck in cryptocurrency "C" which is very very bad.

**Comment by bmino** [comment]
Gotcha, this definitely sounds like an issue. To fix it we would need some safety logic like:

Before executing a trade:
1. Performing 3 executions would not violate the trade limit
2. None of the symbols in the proposed trade are currently being executed

Thoughts?

**Comment by kuuulwin** [comment]
First one understood. But in the second, does that mean that the next execution won't contain the same symbols as a previous one? Because I had profitable trades where the same symbols run in circles for several seconds.

**Comment by bmino** [comment]
I'll use two hypothetical triangle arbitrage pairings here: ABC and DAF.

If you fire off an ABC pairing in parallel and it is still executing (ie all 3 response messages haven't been received yet), then block the execute of something like a DAF pairing because A is currently involved in a transaction.

Once all three trades of ABC return a success response indicating they were executed, then any subsequent requests will not be blocked for involving A, B, or C.

**Comment by bmino** [comment]
There is currently a safety check to block executions of a position (series of 3 trades) if 3 or more trades have been attempted in the past 10 seconds.

The bug with this safety check is that the time logged for the trades is when the trade is sent to be executed. In reality the trade isn't executed until up to a second after the REST request is sent. The real execution time is what Binance cares about for trade execution limits per 10 seconds.

This can be fixed by calculating the trade time after the REST call has completed ensuring we are as accurate as possible

**Comment by bmino** [comment]
Check out release 4.4.5 which should solve your issue :)

**Comment by kuuulwin** [comment]
Should it work for linear execution? I have split the balance into many parts and launched several scripts, to see which one them will get past insufficient balance error. I think the first trades were executed at the same time, some made made it through, others did not.
<img width="505" alt="Screen Shot 2019-04-04 at 12 56 09" src="https://user-images.githubusercontent.com/47988777/55547136-52e2d480-56d9-11e9-8fac-55f8719d0ebf.png">

**Comment by bmino** [comment]
That error you are seeing is a response from Binance. The protections in the bot are only aware of trades made from one instance and cannot protect you from trades made in others.

I would recommend only running one instance of the bot. Even if you have multiple trading accounts on Binance (not sure if that is possible) they might still track orders and bans via ip address

**Comment by moonorblue** [comment]
> Should it work for linear execution? I have split the balance into many parts and launched several scripts, to see which one them will get past insufficient balance error. I think the first trades were executed at the same time, some made made it through, others did not.
> <img alt="Screen Shot 2019-04-04 at 12 56 09" width="505" src="https://user-images.githubusercontent.com/47988777/55547136-52e2d480-56d9-11e9-8fac-55f8719d0ebf.png">

the error should due to you use the same device to run the script, the api call limitation is restricted by ip, try run scripts with multiple devices might help

**Comment by kuuulwin** [comment]
Well, it hasn't helped with parallel either)) running one script and still meeting 10 order limit
I asked Binance and they redirected me here - https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md
There I found this: 
<img width="455" alt="Screen Shot 2019-04-08 at 20 42 54" src="https://user-images.githubusercontent.com/47988777/55744993-f36d2780-5a3e-11e9-9746-8e4d686dcb0f.png">
Maybe this also have something to do with Binance updating their API?

**Comment by bmino** [comment]
I'll look into it further with you. But yeah that's the same docs I was going from. Where you can trade 10 orders per second

**Comment by bmino** [comment]
Hmm I gotta check when I get home, but I think I coded it to protect against 10 trades in 10 seconds by mistake which might explain the issue

**Comment by bmino** [comment]
Check out the new release. Should fix this issue :)
