### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by larrydear** [bmino/binance-triangle-arbitrage#71]
after run a couple of hours in the background, the program will crash with this error.
![image](https://user-images.githubusercontent.com/48785716/61440769-d8cc1800-a976-11e9-8155-e00c2127e03b.png)

RangeError: Maximum call stack size exceeded
    at displayCalculationResults (/home/ubuntu/exchange/binance-triangle-arbitrage/src/main/Main.js:77:65)
    at Timeout.calculateArbitrage [as _onTimeout] (/home/ubuntu/exchange/binance-triangle-arbitrage/src/main/Main.js:61:5)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)

**Comment by bmino** [comment]
Oh baby, that's a doozy! My first suspicion was cpu hardware limitations but upon some reflection this might be a program bug that occurs under certain conditions. Potentially because a record of calculation times is kept for every calculation and over time this can grow to be pretty sizable.

Can I get your config settings for reference please?

**Comment by larrydear** [comment]
yeah,this's my configuration.

{

    "KEYS": {
        "API": "",
        "SECRET": ""
    },

    "INVESTMENT": {
        "BASE": "TFUEL",
        "MIN": 1000,
        "MAX": 10000,
        "STEP": 1000
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "parallel",
        "EXECUTION_TEMPLATE": ["SELL", "SELL", "BUY"],
        "EXECUTION_CAP": 1,
        "TAKER_FEE": 0.075,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": ["TFUEL","BTC", "BNB", "USDT"]
    },

    "HUD": {
        "ENABLED": false,
        "ARB_COUNT": 10
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 75
    },

    "CALCULATION_COOLDOWN": 250

}

**Comment by bmino** [comment]
Thanks, hopefully I'll get some time tonight to bang this one out

**Comment by morison-krw** [comment]
Hi **bmino**. Absolutely mesmerising work you've done here. I don't know if it's worth opening a new issue for, since it's just a suggestion.
You have a depth size config which ranges from 5 to 100. But do you think it would help, if you can also choose how far in the order book you can go for calculation purposes.

Meaning that if your first order is a BUY, I can base my calculations on the average of three ASK prices  or two, five and etc. as well as other legs in the triangle. Thank you!

<img width="435" alt="Screen Shot 2019-07-23 at 23 05 34" src="https://user-images.githubusercontent.com/53236898/61743915-cef34c00-ad9e-11e9-94a1-3b97debaaeb8.png">

**Comment by bmino** [comment]
Release 5.2.2 should fix this issue! Please confirm it has been resolved :)

**Comment by bmino** [comment]
@morison-krw thank you for the kind words, I'm glad you also appreciate this project! Let's discuss that in a separate issue just to keep things clean

**Comment by larrydear** [comment]
Yeah, resolved, my program didn't crash after 2 days.
