### ISSUE TITLE
Ideal Settings...

### ISSUE THREAD

**Issue by angelassets** [bmino/binance-triangle-arbitrage#73]
Hi,
 what would be an Ideal setting? Any guide? Presently using default settings...

**Comment by acongtsai** [comment]
I have tried this setting, there is no error like
Bid depth (0) or ask depth (0) too shallow to convert
because of MIN, MAX, STEP has an effect on errors like
Bid depth (0) or ask depth (0) too shallow to convert
and an unstable internet connection also has an error like
Bid depth (0) or ask depth (0) too shallow to convert

and there are more different settings for btc if we make such settings
"EXECUTION_TEMPLATE": ["BUY", "BUY", "SELL"],
We can make BTC with a small investment
"INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.0003,
        "MAX": 0,0005,
        "STEP": 0,0001
    },
there will be no errors like NOTIONAL
but if we use the settings for btc
"EXECUTION_TEMPLATE": ["BUY", "SELL", "BUY"],
we can't use
"INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.0003,
        "MAX": 0,0005,
        "STEP": 0,0001
    },
because there will be an error like NOTIONAL like lack of balance to be traded
so when using the settings
"EXECUTION_TEMPLATE": ["BUY", "SELL", "BUY"],
we have to use the settings
 "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.0012,
        "MAX": 0.0020,
        "STEP": 0,0001
    },
with settings like this there will be no errors like NOTIONAL but the opportunity for this setting profit plus more occurs in BUY SELL BUY but the investment must be larger and can not use min 0.0003 max 0.0005 step 0.0001

"PROFIT_THRESHOLD": 0.30, because in binance each transaction gets a fee of 0.10 so for tringular transactions 3 x 0.10 = 0.30 if the fee discount with BNB becomes 25% 3 x 0.075 = 0.225
"TAKER_FEE": 0.00,
This is left blank because we already use the profit setting of 0.30

BEST SETTINGS

For USDT

"INVESTMENT": {
        "BASE": "USDT",
        "MIN": 15,
        "MAX": 20,
        "STEP": 1
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["BUY", "SELL", "SELL"],
        "EXECUTION_CAP": 0,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 5
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 100
    },

    "CALCULATION_COOLDOWN": 250

}

For BNB

"INVESTMENT": {
        "BASE": "BNB",
        "MIN": 0.35,
        "MAX": 0.55,
        "STEP": 0.01
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["SELL", "BUY", "SELL"],
        "EXECUTION_CAP": 0,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 5
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 100
    },

    "CALCULATION_COOLDOWN": 250

}

For ETH

    "INVESTMENT": {
        "BASE": "ETH",
        "MIN": 0.05,
        "MAX": 0.10,
        "STEP": 0.01
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["BUY", "SELL", "BUY"],
        "EXECUTION_CAP": 0,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 5
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 100
    },

    "CALCULATION_COOLDOWN": 250

}

For BTC

    "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.0012,
        "MAX": 0.0020,
        "STEP": 0.0001
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["BUY", "SELL", "BUY"],
        "EXECUTION_CAP": 0,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 5
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 100
    },

    "CALCULATION_COOLDOWN": 250

}

**Comment by angelassets** [comment]
Awesome, Thank you, will try these suggestions.

**Comment by acongtsai** [comment]
today => test mode / demo mode for bnb 0.3%

["7/23/2019, 13:27:47"] [32mINFO [39m: [36mAttempting to execute BNB-BTC-REN with an age of -1336 ms and expected profit of 0.3610%[39m
["7/23/2019, 13:27:47"] [32mINFO [39m: [36mTest: Selling 0.41 BNBBTC @ market price[39m
["7/23/2019, 13:27:48"] [32mINFO [39m: [36mTest: Successfully sold BNBBTC @ market price[39m
["7/23/2019, 13:27:48"] [32mINFO [39m: [36mTest: Buying 108 RENBTC @ market price[39m
["7/23/2019, 13:27:48"] [32mINFO [39m: [36mTest: Successfully bought RENBTC @ market price[39m
["7/23/2019, 13:27:48"] [32mINFO [39m: [36mTest: Selling 108 RENBNB @ market price[39m
["7/23/2019, 13:27:48"] [32mINFO [39m: [36mTest: Successfully sold RENBNB @ market price[39m
["7/23/2019, 13:27:48"] [32mINFO [39m: [36mTest: Executed BNB-BTC-REN position in 1444 ms[39m
["7/23/2019, 13:38:32"] [32mINFO [39m: [36mAttempting to execute BNB-USDT-ONE with an age of -1174 ms and expected profit of 0.5565%[39m
["7/23/2019, 13:38:32"] [32mINFO [39m: [36mTest: Selling 0.46 BNBUSDT @ market price[39m
["7/23/2019, 13:38:33"] [32mINFO [39m: [36mTest: Successfully sold BNBUSDT @ market price[39m
["7/23/2019, 13:38:33"] [32mINFO [39m: [36mTest: Buying 1180 ONEUSDT @ market price[39m
["7/23/2019, 13:38:33"] [32mINFO [39m: [36mTest: Successfully bought ONEUSDT @ market price[39m
["7/23/2019, 13:38:33"] [32mINFO [39m: [36mTest: Selling 1180 ONEBNB @ market price[39m
["7/23/2019, 13:38:33"] [32mINFO [39m: [36mTest: Successfully sold ONEBNB @ market price[39m
["7/23/2019, 13:38:33"] [32mINFO [39m: [36mTest: Executed BNB-USDT-ONE position in 1279 ms[39m

**Comment by sergioliberton** [comment]
Sorry, but made a profit from this setting?

**Comment by angelassets** [comment]
I tried these settings on 4 different servers for 3 days now, have lost money in all trades the BOT put in so far...

**Comment by acongtsai** [comment]
This very rapid fluctuation in crypto price changes often makes us lose in the price difference like "PROFIT_THRESHOLD": 0.30, must be increased to run 0.50% or 1%

**Comment by bmino** [comment]
There are pros and cons of most of the settings hence why they are offered as configurable options. For instance using a higher profit threshold will look for more lucrative arbs which will naturally be more competitive as others are looking for the same thing, but with a lower value there is less opportunity for profit and risk of slippage during the execution phase

**Comment by angelassets** [comment]
Hi bmino, any chance you can fix this to do Crex24?

**Comment by bmino** [comment]
What is Crex24?

**Comment by angelassets** [comment]
https://crex24.com
