### ISSUE TITLE
Age Threshold

### ISSUE THREAD

**Issue by kuuulwin** [bmino/binance-triangle-arbitrage#75]
Hello. How come the age of each leg is almost the same or ends up similar to each other, even in execution logs. Are the prices for each tick change at the same time or is there something else at play?

<img width="376" alt="Screen Shot 2019-07-26 at 21 31 23" src="https://user-images.githubusercontent.com/47988777/61973764-87aeca80-afed-11e9-8c2d-15a916a346cf.png">

**Comment by bmino** [comment]
The age of an individual ticker, as I think you are asking here, is the number of milliseconds since a depth websocket has reported information on that particular ticker. Websocket connections are opened in intervals (configured via `INITIALIZATION_INTERVAL`). This means that some websockets will be initialized in such a way that they report at the same time:

Websockets are supposed to report every second so if I opened a websocket for some ticker at t=0ms, then again at t=500ms, then again at t=1000ms, I would expect the first and third websocket to be reporting data at approximately the same time every second.

**Comment by bazan101** [comment]
hum, ok I understand why the startup time is so slow. THX for the good work.

**Comment by bmino** [comment]
@kuuulwin I'll leave this open for you to continue discussion or close it
