### ISSUE TITLE
PROFIT_THRESHOLD

### ISSUE THREAD

**Issue by noahwalugembe** [bmino/binance-triangle-arbitrage#85]
Is this "PROFIT_THRESHOLD": 0.30, appropriate for the 10 BNB investment

 "INVESTMENT": {
        "BASE": "BNB",
        "MIN": 5,
        "MAX": 9,
        "STEP": 0.5
    },

Description: Market taker fee (percent) I cant understand this

**Comment by bmino** [comment]
Please clarify what you are asking. You have mentioned the `PROFIT_THRESHOLD` property, but given the description for `TAKER_FREE`

**Comment by noahwalugembe** [comment]
Is this "PROFIT_THRESHOLD": 0.30, appropriate for the 10 BNB investment

**Comment by bmino** [comment]
`PROFIT_THRESHOLD` will not matter which base currency you are using because it is expressed as a percentage. In all triangle arbitrages, three trades are made. In each of those trades you will lose some profit to fees. This fee is different for each of us depending on our account status, trading volume etc. so the threshold is configurable.

If your fee is 10% (0.10), you wouldn't want to make any trades with less than 30% expected project because you are going to lose 30% (3 x 10%) on fees.

You can also use the `TAKER_FEE` setting to accurately represent fees for your account. If you do this, a `PROFIT_THRESHOLD` of zero would represent a profitable arbitrage.
