### ISSUE TITLE
I need advise on PROFIT_THRESHOLD and AGE_THRESHOLD

### ISSUE THREAD

**Issue by noahwalugembe** [bmino/binance-triangle-arbitrage#86]
are the configurations blow okay for 10 BNB Investment 

"PROFIT_THRESHOLD": 0.20,
 "AGE_THRESHOLD": 50,

**Comment by bmino** [comment]
`PROFIT_THRESHOLD` is expressed as a percent and therefore the base currency won't matter. Higher values will filter out more opportunities, and lower values will include less profitable trades. It's configurable to set as you see fit. Be sure to account for trading fees that will happen on each of the three trades involved.

`AGE_THRESHOLD` of 50 is good. You need to make sure you have a good enough connection (ping) to the exchange or a value so low will exclude all possible trades. Higher values are not really feasible because the market will have shifted too much since the calculations were done
