### ISSUE TITLE
Bot don't work anymore (no trades)

### ISSUE THREAD

**Issue by Qwertzi01** [bmino/binance-triangle-arbitrage#87]
Hi, I tested now the bot over days but the same problems like in issue #68.

No trades during days. Tested all recommended config options. There are
to possible failures all the time in the logs: Depth(0) or Depth(50) too shallow ...

`Depth(0) too shallow` errors with `"SIZE": 100` and `"INITIALIZATION_INTERVAL": 300` or
`Depth(50) too shallow` error with `"SIZE": 50` and `"INITIALIZATION_INTERVAL": 150`

Any ideas/fixes for this problem? Maybe someone with a workaround / working config?

**Comment by bmino** [comment]
Depth (0) failures indicates either:
1. A websocket was initialized incorrectly
2. A websocket has just disconnected

You can increase the initialization interval to aide in this. This issue is something I am looking into still in my free time.


Depth (50) errors indicate that you need to increase your maintained depth cache or decrease your max investment size. You are exhausting all the order book entries attempting to complete a calculation.

**Comment by lulu002** [comment]
I also encountered the same problem and don't know how to deal with it at the moment

**Comment by bmino** [comment]
The depth(50) is not a bug so much as a configuration issue. You can fix this by doing either of the two suggestions I mentioned above.

Let's discuss the depth(0) issue in #68 to keep things concise
